apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-models-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/ollama-models


  # Arquivo de PersistentVolume, usando uma pasta no host (hostPath)
