apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11434
  type: LoadBalancer

# Serviço para os pods do Ollama, do tipo LoadBalancer 
# (conecta um endpoint a todos os ollama, alternando entre eles)